# Generated by Django 4.0.4 on 2022-04-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurementpoint',
            old_name='engine_load',
            new_name='ENGINE_LOAD',
        ),
        migrations.RenameField(
            model_name='measurementpoint',
            old_name='maf',
            new_name='MAF',
        ),
        migrations.RenameField(
            model_name='measurementpoint',
            old_name='rpm',
            new_name='RPM',
        ),
        migrations.RenameField(
            model_name='measurementpoint',
            old_name='speed',
            new_name='SPEED',
        ),
        migrations.RenameField(
            model_name='measurementpoint',
            old_name='throttle_pos',
            new_name='THROTTLE_POS',
        ),
    ]
