# Generated by Django 4.0.4 on 2022-06-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_raspberry',
            field=models.BooleanField(default=False),
        ),
    ]
