# Generated by Django 4.0.4 on 2022-06-13 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raspberry', '0002_alter_raspberry_used_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberry',
            name='raspberry_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raspberry', to=settings.AUTH_USER_MODEL),
        ),
    ]
